# Package Overview
package_name: titanic_classification

# Data Files
training_data_file: raw.csv
test_data_file: raw.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: titanic_classification
pipeline_save_file: titanic_classification_v

# Will cause syntax errors since they begin with numbers
#variables_to_rename:
#  1stFlrSF: FirstFlrSF
#  2ndFlrSF: SecondFlrSF
#  3SsnPorch: ThreeSsnPortch

features:
  - fare
  - age
  - pclass
  - sex
  - sibsp
  - parch
  - embarked
  - title
  - cabin

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

alpha: 0.001

numerical_vars:
  - fare
  - age

categorical_vars:
  - pclass
  - sex
  - sibsp
  - parch
  - embarked
  - title

cabin_vars:
  - cabin

# categorical variables with NA in train set
#categorical_vars_with_na_frequent:
#  - BsmtQual
#  - BsmtExposure
#  - BsmtFinType1
#  - GarageFinish
#
#categorical_vars_with_na_missing:
#  - FireplaceQu
#
#numerical_vars_with_na:
#  - LotFrontage
#
#temporal_vars:
#  - YearRemodAdd
#
#ref_var: YrSold
#
#
## variables to log transform
#numericals_log_vars:
#  - LotFrontage
#  - FirstFlrSF
#  - GrLivArea
#
#binarize_vars:
#  - ScreenPorch
#
## variables to map
#qual_vars:
#  - ExterQual
#  - BsmtQual
#  - HeatingQC
#  - KitchenQual
#  - FireplaceQu
#
#exposure_vars:
#  - BsmtExposure
#
#finish_vars:
#  - BsmtFinType1
#
#garage_vars:
#  - GarageFinish
#


# variable mappings
#qual_mappings:
#  Po: 1
#  Fa: 2
#  TA: 3
#  Gd: 4
#  Ex: 5
#  Missing: 0
#  NA: 0
#
#exposure_mappings:
#  No: 1
#  Mn: 2
#  Av: 3
#  Gd: 4
#
#
#finish_mappings:
#  Missing: 0
#  NA: 0
#  Unf: 1
#  LwQ: 2
#  Rec: 3
#  BLQ: 4
#  ALQ: 5
#  GLQ: 6
#
#
#garage_mappings:
#  Missing: 0
#  NA: 0
#  Unf: 1
#  RFn: 2
#  Fin: 3
